In [1]:
import pandas as pd

In [2]:
import os
import sys

sys.path.append(os.path.abspath(".."))

In [33]:
from banco.conexao import engine

In [3]:
from api.api import buscar_dados

In [4]:
df = buscar_dados()

In [5]:
df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,40,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png

In [6]:
df.shape

(194, 27)

In [7]:
df.drop(
    columns=[
        "images",
        "thumbnail",
        "reviews",
        "meta",
        "returnPolicy",
        "shippingInformation",
        "warrantyInformation"
    ],
    inplace=True,
    errors="ignore"
)

In [8]:
df.shape

(194, 21)

In [9]:
print(df.columns.tolist())

['id', 'title', 'description', 'category', 'price', 'discountPercentage', 'rating', 'stock', 'tags', 'brand', 'sku', 'weight', 'availabilityStatus', 'minimumOrderQuantity', 'dimensions.width', 'dimensions.height', 'dimensions.depth', 'meta.createdAt', 'meta.updatedAt', 'meta.barcode', 'meta.qrCode']

In [10]:
df.rename(columns= {
    "id": "product_id",
    "title": "product_name",
    "description": "description",
    "category": "category",
    "price": "price",
    "discountPercentage": "discount_percentage",
    "rating": "rating",
    "stock": "stock",
    "tags": "tags",
    "brand": "brand",
    "sku": "sku",
    "weight": "weight",
    "availabilityStatus": "availability_status",
    "minimumOrderQuantity": "minimum_order_quantity",
    "dimensions.width": "width",
    "dimensions.height": "height",
    "dimensions.depth": "depth",
    "meta.createdAt": "created_at",
    "meta.updatedAt": "updated_at",
    "meta.barcode": "barcode",
    "meta.qrCode": "qr_code"
}, inplace=True)

In [11]:
df.isnull().sum()

product_id                 0
product_name               0
description                0
category                   0
price                      0
discount_percentage        0
rating                     0
stock                      0
tags                       0
brand                     92
sku                        0
weight                     0
availability_status        0
minimum_order_quantity     0
width                      0
height                     0
depth                      0
created_at                 0
updated_at                 0
barcode                    0
qr_code                    0
dtype: int64

In [12]:
df['brand'] = df['brand'].fillna("Unknown")

In [13]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of      product_id                   product_name  \
0             1  Essence Mascara Lash Princess
1             2  Eyeshadow Palette with Mirror
2             3                Powder Canister
3             4                   Red Lipstick
4             5                Red Nail Polish
..          ...                            ...
189         190  IWC Ingenieur Automatic Steel
190         191        Rolex Cellini Moonphase
191         192           Rolex Datejust Women
192         193           Watch Gold for Women
193         194            Women's Wrist Watch

                                           description        category  \
0    The Essence Mascara Lash Princess is a popular...          beauty
1    The Eyeshadow Palette with Mirror offers a ver...          beauty
2    The Powder Canister is a finely milled setting...          beauty
3    The Red Lipstick is a classic and bold choice ...          beauty
4    The Red Nail Polish offers a rich and glossy r...          beauty
..                                                 ...             ...
189  The IWC Ingenieur Automatic Steel watch is a d...  womens-watches
190  The Rolex Cellini Moonphase watch is a masterp...  womens-watches
191  The Rolex Datejust Women's watch is an iconic ...  womens-watches
192  The Gold Women's Watch is a stunning accessory...  womens-watches
193  The Women's Wrist Watch is a versatile and fas...  womens-watches

        price  discount_percentage  rating  stock  \
0        9.99                10.48    2.56     99
1       19.99                18.19    2.86     34
2       14.99                 9.84    4.64     89
3       12.99                12.16    4.36     91
4        8.99                11.44    4.32     79
..        ...                  ...     ...    ...
189   4999.99                 9.45    2.93     90
190  15999.99                 4.11    3.83     52
191  10999.99                15.94    2.86      4
192    799.99                18.34    4.24      0
193    129.99                12.60    3.52     12

                                           tags           brand  ... weight  \
0                             [beauty, mascara]         Essence  ...      4
1                           [beauty, eyeshadow]  Glamour Beauty  ...      9
2                         [beauty, face powder]    Velvet Touch  ...      8
3                            [beauty, lipstick]  Chic Cosmetics  ...      1
4                         [beauty, nail polish]    Nail Couture  ...      8
..                                          ...             ...  ...    ...
189                   [watches, luxury watches]             IWC  ...      3
190                   [watches, luxury watches]           Rolex  ...     10
191  [watches, luxury watches, women's watches]           Rolex  ...      3
192                  [watches, women's watches]    Fashion Gold  ...      1
193                  [watches, women's watches]     Fashion Co.  ...      1

     availability_status minimum_order_quantity  width  height  depth  \
0               In Stock                     48  15.14   13.08  22.99
1               In Stock                     20   9.26   22.47  27.67
2               In Stock                     22  29.27   27.93  20.59
3               In Stock                     40  18.11   28.38  22.17
4               In Stock                     22  21.63   16.48  29.84
..                   ...                    ...    ...     ...    ...
189             In Stock                      1  24.77   24.66   6.09
190             In Stock                      1  12.50   20.63  25.04
191            Low Stock                      1  23.23    7.19  28.95
192         Out of Stock                      1  18.85   28.59   7.21
193             In Stock                      5  26.10   22.03  21.61

                   created_at                updated_at        barcode  \
0    2025-04-30T09:41:02.053Z  2025-04-30T09:41:02.053Z  5784719087687
1    2025-04-30T09:41:02.053Z  2025-04-30T09:41:02.053Z  9170275171413
2    2025-04-30T09:41:02.053Z  2025-04-30T09:41:02.053Z  8418883906837
3    2025-04-30T09:41:02.053Z  2025-04-30T09:41:02.053Z  9467746727219
4    2025-04-30T09:41:02.053Z  2025-04-30T09:41:02.053Z  4063010628104
..                        ...                       ...            ...
189  2025-04-30T09:41:02.054Z  2025-04-30T09:41:02.054Z  7438522857639
190  2025-04-30T09:41:02.054Z  2025-04-30T09:41:02.054Z  4608359670564
191  2025-04-30T09:41:02.054Z  2025-04-30T09:41:02.054Z  1265605585958
192  2025-04-30T09:41:02.054Z  2025-04-30T09:41:02.054Z  8333241081413
193  2025-04-30T09:41:02.054Z  2025-04-30T09:41:02.054Z  2093537854573

                                          qr_code
0    https://cdn.dummyjson.com/public/qr-code.png
1    https://cdn.dummyjson.com/public/qr-code.png
2    https://cdn.dummyjson.com/public/qr-code.png
3    https://cdn.dummyjson.com/public/qr-code.png
4    https://cdn.dummyjson.com/public/qr-code.png
..                                            ...
189  https://cdn.dummyjson.com/public/qr-code.png
190  https://cdn.dummyjson.com/public/qr-code.png
191  https://cdn.dummyjson.com/public/qr-code.png
192  https://cdn.dummyjson.com/public/qr-code.png
193  https://cdn.dummyjson.com/public/qr-code.png

[194 rows x 21 columns]>

In [14]:
df.head()

,product_id,product_name,description,category,price,discount_percentage,rating,stock,tags,brand,...,weight,availability_status,minimum_order_quantity,width,height,depth,created_at,updated_at,barcode,qr_code
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,4,In Stock,48,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,9,In Stock,20,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,8,In Stock,22,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,1,In Stock,40,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,8,In Stock,22,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png

In [15]:
df.columns

Index(['product_id', 'product_name', 'description', 'category', 'price',
       'discount_percentage', 'rating', 'stock', 'tags', 'brand', 'sku',
       'weight', 'availability_status', 'minimum_order_quantity', 'width',
       'height', 'depth', 'created_at', 'updated_at', 'barcode', 'qr_code'],
      dtype='str')

In [16]:
df.drop(columns=["barcode", "qr_code", "width", "height", "depth"], inplace=True)

In [17]:
df.head()

,product_id,product_name,description,category,price,discount_percentage,rating,stock,tags,brand,sku,weight,availability_status,minimum_order_quantity,created_at,updated_at
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,BEA-ESS-ESS-001,4,In Stock,48,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,BEA-GLA-EYE-002,9,In Stock,20,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,BEA-VEL-POW-003,8,In Stock,22,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,BEA-CHI-LIP-004,1,In Stock,40,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,BEA-NAI-NAI-005,8,In Stock,22,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z

In [18]:
df["tags"] = df["tags"].apply(lambda x: ", ".join(x))

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              194 non-null    int64
 1   product_name            194 non-null    str
 2   description             194 non-null    str
 3   category                194 non-null    str
 4   price                   194 non-null    float64
 5   discount_percentage     194 non-null    float64
 6   rating                  194 non-null    float64
 7   stock                   194 non-null    int64
 8   tags                    194 non-null    str
 9   brand                   194 non-null    str
 10  sku                     194 non-null    str
 11  weight                  194 non-null    int64
 12  availability_status     194 non-null    str
 13  minimum_order_quantity  194 non-null    int64
 14  created_at              194 non-null    str
 15  updated_at              194 non-null    str
dtypes: float64(3), int64(4), str(9)
memory usage: 24.4 KB

In [24]:
df['minimum_order_quantity'] = df['minimum_order_quantity'].astype(int)
df['created_at'] = pd.to_datetime(df['created_at'])
df['updated_at'] = pd.to_datetime(df['updated_at'])
df["price"] = df["price"].astype(float).round(2)
df["discount_percentage"] = df["discount_percentage"].astype(float).round(2)
df["rating"] = df["rating"].astype(float).round(2)
df["weight"] = df["weight"].astype(float)

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              194 non-null    int64
 1   product_name            194 non-null    str
 2   description             194 non-null    str
 3   category                194 non-null    str
 4   price                   194 non-null    float64
 5   discount_percentage     194 non-null    float64
 6   rating                  194 non-null    float64
 7   stock                   194 non-null    int64
 8   tags                    194 non-null    str
 9   brand                   194 non-null    str
 10  sku                     194 non-null    str
 11  weight                  194 non-null    float64
 12  availability_status     194 non-null    str
 13  minimum_order_quantity  194 non-null    int64
 14  created_at              194 non-null    datetime64[us, UTC]
 15  updated_at              194 non-null    datetime64[us, UTC]
dtypes: datetime64[us, UTC](2), float64(4), int64(3), str(7)
memory usage: 24.4 KB

In [30]:
from datetime import datetime, timezone

df["collection_date"] = datetime.now(timezone.utc)

In [27]:
#SEPARANDO EM DATAFRAMES PARA ADICIONAR NO BANCO(FORMA MAIS ORGANIZADA E LIMPA)

In [28]:
df_products = df[
    [
        "product_id",
        "product_name",
        "description",
        "category",
        "brand",
        "sku",
        "weight",
        "minimum_order_quantity",
        "tags",
        "created_at"
    ]
]

In [31]:
df_price_history = df[
    [
        "product_id",
        "price",
        "discount_percentage",
        "updated_at",
        "collection_date"
    ]
]

In [32]:
df_stock_history = df[
    [
        "product_id",
        "stock",
        "availability_status",
        "collection_date"
    ]
]

In [ ]:
#ADICIONANDO DADOS NA TABELA

In [34]:
df_products.to_sql(
    name="products",
    con=engine,
    if_exists="append",
    index=False
)

194

In [35]:
df_price_history.to_sql(
    name = "price_history",
    con=engine,
    if_exists="append",
    index=False
)

194

In [36]:
df_stock_history.to_sql(
    name = "stock_history",
    con=engine,
    if_exists="append",
    index=False
)

194